### ISSUE TITLE
jasmineClean seems to do more than "Removes generated karma config file"

### ISSUE THREAD

**Issue by marchaos** [craigburke/jasmine-gradle#1]
Hey. 

Firstly some feedback. Just started using this and was able to get my tests running. I'm on a mac, and it all seems to be working fine. 

When I run my tests, if I make a change to jasmine {} block in build.gradle, it looks like I have to run jasmineClean to pick up those changes. When doing this, I can see that node is compiling stuff in the background. Is this necessary?

**Comment by craigburke** [comment]
@marchaos that's a good point. 

I think I should probably add a separate `jasmineRefresh` task that would regenerate the config file but not force all the dependencies to be pulled in like `jasmineClean` does.

Thanks for the feedback!

**Comment by craigburke** [comment]
@marchaos ok, I added a jasmineRefresh task that just updates the karma config (https://github.com/craigburke/jasmine-gradle/commit/a712f7c9a89fede6cadc067cbf83e0888501934d). 

I haven't published this yet so feel free to send any feedback you have and I'll publish 1.2.0 later this evening.

**Comment by craigburke** [comment]
Resolved in version 1.2.0
