### ISSUE TITLE
Add option for karma-junit-reporter

### ISSUE THREAD

**Issue by craigburke** [craigburke/jasmine-gradle#2]
Hi @alejoHomes, I just saw your fork. Do you think it makes sense to add an option to my plugin to bring in those same dependencies?

**Comment by alejoHomes** [comment]
Hi craigburke. 

Thanks for you plugin, it's was helpful for the test that I did.
I'm newer in gradle and jasmine, and I needed integrate the xml reporter.

First, try to integrate manually with npm, and work. But to build in jenkins it's was necessary to added in the dependencies.

The fork was the faster solution, I apologize for not request you.

**Comment by craigburke** [comment]
@alejoHomes: No worries, man, I'm just trying to figure out if it makes sense to make any addition on my side.

My documentation isn't as complete as it could be, you probably could have accomplished the same thing with my plugin by adding those dependencies directly in your config like this:
```
jasmine {
    dependencies += ['karma-junit-reporter', 'karma-qunit']
    frameworks += 'qunit'
}
```
I need to at least add something like that to the README. 

I'm wondering if it makes sense to add an option for alternate testing frameworks to make that a little easier. Still thinking through what that would look like. Definitely open to suggestions on that.

**Comment by alejoHomes** [comment]
Ok,

great, that's a  elegant solution.

**Comment by craigburke** [comment]
@alejoHomes let me know if that works, or if I need to add anything on my end so it works better for you.

**Comment by alejoHomes** [comment]
yes, that works. 

thanks.

**Comment by ColinHarrington** [comment]
I don't think its necessary to add the extra dependencies if the configuration mechanism is easy and documented well.

**Comment by craigburke** [comment]
@ColinHarrington so your suggestion is that I should better document what's already there? Do you think there's utility in adding additional configuration options?

**Comment by craigburke** [comment]
@alejoHomes I have a new gradle plugin that I think will eliminate the need for you to maintain your own fork, check out the karma gradle plugin:
https://github.com/craigburke/karma-gradle

I'd love to hear what you think of this one.
