### ISSUE TITLE
Generate JUnit style XML for CI tools to pickup

### ISSUE THREAD

**Issue by rahulsom** [craigburke/jasmine-gradle#3]
Thanks for this awesome plugin. Saved me from the js build tools masochism. 
Do you have any documentation on generating junit style xml reports?

**Comment by craigburke** [comment]
@rahulsom cool! Glad you like it!

I've played around with the various settings, but I need to return to that and beef up the documentation and come up with some more formal examples.

**Comment by craigburke** [comment]
I should put a note on this project. I've deprecated it in favor of this:
https://github.com/craigburke/karma-gradle

**Comment by rahulsom** [comment]
Thanks!
